services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: piyushkr11/health-monitor:frontend
    ports:
      - "3000:80"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: piyushkr11/health-monitor:backend
    ports:
      - "5020:5020"

  ai-agent:
    build:
      context: ./ai-agent
      dockerfile: Dockerfile
    image: piyushkr11/health-monitor:ai-agent
    ports:
      - "6000:6000"

  db:
    image: mongo:6
    volumes:
      - ./health-monitor:/data/db
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml